### ISSUE TITLE
The build file contains an absolute path

### ISSUE THREAD

**Issue by PicaQQQ** [HexHive/FuZZan#1]
*FuZZan/etc/libshrink/build.sh*

`/home/jeon41/FuZZan/LLVM/build/bin/clang++ ctor.cpp -o test -mcmodel=small -fsanitize=address -g -O2`

Change to

`../../LLVM/build/bin/clang++ ctor.cpp -o test -mcmodel=small -fsanitize=address -g -O2`

**Comment by jys0710** [comment]
Thanks for your report. I fixed it.
