### ISSUE TITLE
compiling fails

### ISSUE THREAD

**Issue by adrian-rt** [HexHive/FuZZan#2]
Hi all,

Compiling fails with the error below, any ideas/

what compiler did you use? thanks.

30 warnings generated.
[1240/3690] Building CXX object projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.x86_64.dir/sanitizer_platform_limits_posix.cc.o
FAILED: projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.x86_64.dir/sanitizer_platform_limits_posix.cc.o 
/usr/local/bin/clang++  -DHAVE_RPC_XDR_H=0 -DHAVE_TIRPC_RPC_XDR_H=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/compiler-rt/lib/sanitizer_common -I/home/adrian/Downloads/fuzzers/FuZZan-master/LLVM/llvm/projects/compiler-rt/lib/sanitizer_common -I/usr/include/libxml2 -Iinclude -I/home/adrian/Downloads/fuzzers/FuZZan-master/LLVM/llvm/include -I/home/adrian/Downloads/fuzzers/FuZZan-master/LLVM/llvm/projects/compiler-rt/lib/sanitizer_common/.. -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -std=c++11 -Wno-unused-parameter -O3 -DNDEBUG     -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -std=c++11 -Wno-unused-parameter -m64 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -Wno-non-virtual-dtor -DFMODE1 -fno-rtti -Wframe-larger-than=570 -Wglobal-constructors -MD -MT projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.x86_64.dir/sanitizer_platform_limits_posix.cc.o -MF projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.x86_64.dir/sanitizer_platform_limits_posix.cc.o.d -o projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.x86_64.dir/sanitizer_platform_limits_posix.cc.o -c /home/adrian/Downloads/fuzzers/FuZZan-master/LLVM/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc
/home/adrian/Downloads/fuzzers/FuZZan-master/LLVM/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:1163:1: error: 'assertion_failed__1163' declared as an array with a negative size
CHECK_SIZE_AND_OFFSET(ipc_perm, mode);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/adrian/Downloads/fuzzers/FuZZan-master/LLVM/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.h:1513:3: note: expanded from macro 'CHECK_SIZE_AND_OFFSET'
  COMPILER_CHECK(sizeof(((__sanitizer_##CLASS *) NULL)->MEMBER) == \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/adrian/Downloads/fuzzers/FuZZan-master/LLVM/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_internal_defs.h:336:30: note: expanded from macro 'COMPILER_CHECK'
#define COMPILER_CHECK(pred) IMPL_COMPILER_ASSERT(pred, __LINE__)
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/adrian/Downloads/fuzzers/FuZZan-master/LLVM/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_internal_defs.h:342:57: note: expanded from macro 'IMPL_COMPILER_ASSERT'
    typedef char IMPL_PASTE(assertion_failed_##_, line)[2*(int)(pred)-1]
                                                        ^~~~~~~~~~~~~~~
1 error generated.
[1252/3690] Building CXX object lib/ProfileData/Coverage/CMakeFiles/LLVMCoverage.dir/CoverageMapping.cpp.o

**Comment by adrian-rt** [comment]
ps:  apparently LLVM_ENABLE_ASSERTIONS doesn't work in the Makefile.....

**Comment by jys0710** [comment]
Thanks for your report. I will address this issue by this week.

**Comment by adrian-rt** [comment]
hi @jys0710 ,

any updates on the above issue please?

thank you.

**Comment by jys0710** [comment]
I tried to reproduce this issue. However, I did not find any issues during my FuZZan reinstallation.
I installed FuZZan using Ubuntu 19.10.
Did you try to install FuZZan using Ubuntu 19.10?

**Comment by adrian-rt** [comment]
I can't, I'm already on Ubuntu 20.04, please see below.

 cat /etc/os-release 
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by jys0710** [comment]
Could you please test with 19.10 as we did not test with 20.04?

**Comment by adrian-rt** [comment]
@jys0710 ,

this seems impossible at the moment. It seems to be only possible to upgrade  from Ubuntu 18 to Ubuntu 20, or the other way around.

There is no official Docker container for ubuntu 19 either.

**Comment by jys0710** [comment]
If you don't mind, could you please test FuZZan with VM player and ubuntu 19.10 image first?
- http://old-releases.ubuntu.com/releases/19.10/
FuZZan's porting works (from 19.20 to 20.x) will take time.

**Comment by jys0710** [comment]
I fixed this issue (https://github.com/HexHive/FuZZan/commit/39f04ef4f6b68eb1bf8affb13754f7fc971b4d45). Please use git pull and build it again.
